### ISSUE TITLE
only works half of the time

### ISSUE THREAD

**Issue by buleva** [jacamera/disable-youtube-watch-later-autoplay#3]
Hey, I use Brave Browser instead of Chrome and I am on macos 14 right now. Somehow the extension doesn't work all of the time, but I couldn't figure out what the reason behind this is. If I find out, I will let you know.

Thanks for your work and have a nice day!

**Comment by jacamera** [comment]
Hey, thanks for the report! I think I might have found the issue. Does it happen when you click on the metadata below the video title on your watch later list instead of the actual title itself or thumbnail image? For instance: "123K views • 1 day ago". It looks like those elements may be causing an issue with the click detection/interception.

**Comment by buleva** [comment]
Your right. It’s only when I click on those. Thumbnail and title works fine.

**Comment by jacamera** [comment]
This should be fixed in version 1.0.4. Clicking anywhere within the video card element should now work as expected.
